# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml==6.0.2"]
# ///
"""Seed fallback Sparkle feeds from Homebrew casks whose livecheck reads a Sparkle appcast.

    git clone --depth 1 https://github.com/Homebrew/homebrew-cask.git /tmp/homebrew-cask
    uv run scripts/import_livecheck.py --casks /tmp/homebrew-cask --ripe "$(which ripe)" --dry-run
    uv run scripts/import_livecheck.py ... --only keepingyouawake     # write entries for these casks

Writing needs `--only`: orchard stays a curated catalog, so an entry is added when someone has a
reason for it (a `ripe why` report, an app known to set its feed in code), never in bulk. A dry
run over every cask shows which ones would pass.

The cask JSON API leaves livecheck out, so feed URLs come from the casks' Ruby source; the
rest (version, app name, bundle IDs) comes from the API. A feed is written only when:

- the cask is a stable channel (no `@` in its token), not disabled or deprecated, installs
  exactly one app, and serves the same feed on every CPU;
- its livecheck URL is a plain https:// string (no Ruby interpolation);
- the app's bundle ID is unambiguous (see `bundle_id`), and no other cask claims it;
- no hand-written entry exists for that bundle ID;
- the release Ripe itself takes from the feed (`ripe feed`) matches the cask's version.

Entries are written as `fallback_sparkle_feed`: Ripe uses them only for apps that declare no
feed of their own, and compares them cautiously. Files this script writes start with
GENERATED_MARKER; delete that line to take a file over by hand, and the importer leaves it alone.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.request
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import build

ROOT = Path(__file__).resolve().parent.parent
CASK_API = "https://formulae.brew.sh/api/cask.json"
GENERATED_MARKER = "# Generated by scripts/import_livecheck.py"
BUNDLE_ID = re.compile(r"^[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+$")
FEED_BATCH = 100


@dataclass(frozen=True)
class Candidate:
    token: str
    name: str
    bundle_id: str
    feed: str
    cask_version: str


@dataclass(frozen=True)
class FeedResult:
    version: str | None
    build: str | None
    error: str | None


def livecheck_feeds(casks_dir: Path) -> dict[str, str | None]:
    """Cask token -> literal Sparkle feed URL, or None when the cask uses Sparkle but its feed
    can't be taken as-is (interpolated, or different per CPU)."""
    feeds: dict[str, str | None] = {}
    for path in sorted((casks_dir / "Casks").rglob("*.rb")):
        feeds.update(parse_cask_source(path.stem, path.read_text(encoding="utf-8")))
    return feeds


def parse_cask_source(token: str, source: str) -> dict[str, str | None]:
    block = re.search(r"\n  livecheck do\n(.*?)\n  end\n", source, re.S)
    if not block or "strategy :sparkle" not in block.group(1):
        return {}
    url = re.search(r'^\s*url\s+"([^"]*)"\s*$', block.group(1), re.M)
    if not url or "#{" in url.group(1) or re.search(r"^\s*on_(arm|intel)\b", source, re.M):
        return {token: None}
    return {token: url.group(1)}


def app_name(cask: dict) -> str | None:
    """The single app a cask installs, as Finder shows it, or None."""
    apps = [artifact["app"] for artifact in cask.get("artifacts", []) if "app" in artifact]
    if len(apps) != 1:
        return None
    names = [item for item in apps[0] if isinstance(item, str)]
    targets = [item["target"] for item in apps[0] if isinstance(item, dict) and "target" in item]
    if len(names) != 1:
        return None
    name = (targets[0] if targets else names[0]).rsplit("/", 1)[-1]
    return name[: -len(".app")] if name.endswith(".app") else None


def bundle_id(cask: dict) -> str | None:
    """The app's bundle ID, only when the cask makes it unambiguous.

    `uninstall quit` names the running app's ID. Several quit IDs (an app and its helpers) are
    narrowed by the preferences files `zap` removes. Without any, a single preferences file, or
    a single ID with both preferences and a saved window state, names the app. Ripe applies a
    seeded entry only when the app's Finder name matches too, so a wrong guess attaches to nothing.
    """
    quit_ids: set[str] = set()
    zap_paths: list[str] = []
    for artifact in cask.get("artifacts", []):
        for directive in artifact.get("uninstall", []):
            if isinstance(directive, dict):
                quit_ids.update(as_list(directive.get("quit")))
        for directive in artifact.get("zap", []):
            if isinstance(directive, dict):
                zap_paths.extend(as_list(directive.get("trash")))
    quit_ids = {value for value in quit_ids if usable_id(value)}
    prefs = {value for value in ids_in(zap_paths, r"^~/Library/Preferences/(.+)\.plist$") if usable_id(value)}
    saved = set(ids_in(zap_paths, r"^~/Library/Saved Application State/(.+)\.savedState$"))
    for pool in (quit_ids, quit_ids & prefs) if quit_ids else (prefs, prefs & saved):
        if len(pool) == 1:
            return next(iter(pool))
    return None


def as_list(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [item for item in value if isinstance(item, str)]
    return []


def ids_in(paths: list[str], pattern: str) -> list[str]:
    return [match.group(1) for path in paths if (match := re.match(pattern, path))]


def usable_id(value: str) -> bool:
    return bool(BUNDLE_ID.match(value)) and not value.lower().startswith("com.apple.")


def plausible(identifier: str, name: str) -> bool:
    """Rejects IDs zap and quit lists use for things other than the app itself: Team-ID-prefixed
    app groups (`5YKZ4Y3DAW.group.com.intii.CopilotForXcode`), the app's file name (`Herd.app`)
    and helpers (`com.hezongyidev.BobHelper` for Bob)."""
    last = identifier.rsplit(".", 1)[-1].lower()
    if re.match(r"^[A-Z0-9]{10}\.", identifier) or ".group." in f".{identifier.lower()}.":
        return False
    if identifier.lower() == f"{name.lower()}.app":
        return False
    return not ("helper" in last and "helper" not in name.lower())


def candidates(casks: list[dict], feeds: dict[str, str | None], existing: set[str]) -> tuple[list[Candidate], dict[str, str]]:
    """Casks worth checking, and why every other Sparkle cask was left out."""
    skipped: dict[str, str] = {}
    found: list[Candidate] = []
    by_token = {cask["token"]: cask for cask in casks}
    for token, feed in sorted(feeds.items()):
        cask = by_token.get(token)
        reason = None
        if cask is None:
            reason = "not in the cask API"
        elif "@" in token:
            reason = "not the stable channel"
        elif cask.get("disabled") or cask.get("deprecated"):
            reason = "disabled or deprecated"
        elif feed is None:
            reason = "feed URL is computed or differs per CPU"
        elif not feed.startswith("https://"):
            reason = "feed is not https"
        elif (name := app_name(cask)) is None:
            reason = "doesn't install exactly one app"
        elif (identifier := bundle_id(cask)) is None:
            reason = "bundle ID is ambiguous"
        elif not plausible(identifier, name):
            reason = "bundle ID looks like a helper or group, not the app"
        elif identifier.lower() in existing:
            reason = "hand-written entry exists"
        if reason:
            skipped[token] = reason
            continue
        found.append(Candidate(token, name, identifier, feed, cask["version"]))

    # Two casks claiming one bundle ID: neither is trusted.
    counts: dict[str, int] = {}
    for candidate in found:
        counts[candidate.bundle_id.lower()] = counts.get(candidate.bundle_id.lower(), 0) + 1
    unique = []
    for candidate in found:
        if counts[candidate.bundle_id.lower()] > 1:
            skipped[candidate.token] = "another cask claims the same bundle ID"
        else:
            unique.append(candidate)
    return unique, skipped


def normalize(version: str) -> str:
    version = version.strip().removeprefix("v")
    while version.endswith(".0") and version.count(".") > 0:
        version = version[:-2]
    return version


def leading_version(value: str) -> str:
    """`3.29.2` of `3.29.2(400)`, `1.167.0 (88045)` or `3.10.8 :0294d207:`; Ripe ignores the rest too."""
    match = re.match(r"v?\d+(\.\d+)*", value.strip())
    return match.group(0) if match else value


def matches_cask(cask_version: str, feed: FeedResult) -> bool:
    """The feed's release is the cask's version: the visible version or the build number equals
    the cask's first part (`1.9.5` of `1.9.5,88`). A feed whose newest release is something
    else is one Ripe would read differently from Homebrew, so it isn't used."""
    short = normalize(cask_version.split(",")[0])
    return any(
        value is not None and normalize(leading_version(value)) == short for value in (feed.version, feed.build)
    )


def check_feeds(ripe: str, urls: list[str]) -> dict[str, FeedResult]:
    results: dict[str, FeedResult] = {}
    for start in range(0, len(urls), FEED_BATCH):
        batch = urls[start : start + FEED_BATCH]
        output = subprocess.run([ripe, "feed", "--refresh", *batch], check=True, capture_output=True, text=True).stdout
        for line in output.splitlines():
            item = json.loads(line)
            results[item["url"]] = FeedResult(item.get("version"), item.get("build"), item.get("error"))
        print(f"checked {min(start + FEED_BATCH, len(urls))}/{len(urls)} feeds", file=sys.stderr)
    return results


def render(candidate: Candidate, feed: FeedResult, today: date) -> str:
    release = feed.version if not feed.build or feed.build == feed.version else f"{feed.version}, build {feed.build}"
    return (
        f"{GENERATED_MARKER} from Homebrew cask `{candidate.token}`.\n"
        f"# Verified {today.isoformat()}: the feed's newest release for a Mac ({release}) matched the cask.\n"
        f"bundle_id: {candidate.bundle_id}\n"
        f"name: {yaml_string(candidate.name)}\n"
        f"fallback_sparkle_feed: {candidate.feed}\n"
    )


def yaml_string(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9 ._()+-]*", value) and not value.endswith(" "):
        return value
    return json.dumps(value, ensure_ascii=False)


def body(text: str) -> str:
    """A file without its comment lines: what decides whether rewriting it changes anything."""
    return "".join(line for line in text.splitlines(keepends=True) if not line.startswith("#"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--casks", type=Path, required=True, help="a homebrew-cask checkout")
    parser.add_argument("--ripe", required=True, help="path to a ripe binary that has `ripe feed`")
    parser.add_argument("--cask-json", type=Path, help="a saved copy of the cask API (default: download)")
    parser.add_argument("--dry-run", action="store_true", help="report only, write nothing")
    parser.add_argument("--only", action="append", default=[], help="cask token(s) to write, comma-separated")
    args = parser.parse_args()
    only = {token.strip() for value in args.only for token in value.split(",") if token.strip()}
    if not only and not args.dry_run:
        parser.error("name the casks to add with --only (or use --dry-run to survey every cask)")

    apps_dir = ROOT / "apps"
    generated, handwritten = set(), set()
    for path in apps_dir.glob("*.yml"):
        owner = generated if path.read_text(encoding="utf-8").startswith(GENERATED_MARKER) else handwritten
        owner.add(path.stem.lower())

    if args.cask_json:
        casks = json.loads(args.cask_json.read_text(encoding="utf-8"))
    else:
        with urllib.request.urlopen(CASK_API, timeout=60) as response:
            casks = json.load(response)

    feeds = livecheck_feeds(args.casks)
    if only:
        missing = only - set(feeds)
        if missing:
            parser.error(f"no Sparkle livecheck in: {', '.join(sorted(missing))}")
        feeds = {token: url for token, url in feeds.items() if token in only}
    found, skipped = candidates(casks, feeds, handwritten)
    results = check_feeds(args.ripe, sorted({candidate.feed for candidate in found}))

    today = date.today()
    written = unchanged = 0
    verified: set[str] = set()
    for candidate in found:
        feed = results.get(candidate.feed, FeedResult(None, None, "not checked"))
        if feed.error:
            skipped[candidate.token] = f"feed failed: {feed.error}"
            continue
        if not matches_cask(candidate.cask_version, feed):
            skipped[candidate.token] = f"feed offers {feed.version} (build {feed.build}), cask says {candidate.cask_version}"
            continue
        path = apps_dir / f"{candidate.bundle_id}.yml"
        text = render(candidate, feed, today)
        try:
            build.compile_entry(path, build.yaml.safe_load(text))
        except build.Invalid as error:
            skipped[candidate.token] = f"rejected by build.py: {error}"
            continue
        verified.add(candidate.bundle_id.lower())
        if path.exists() and body(path.read_text(encoding="utf-8")) == body(text):
            unchanged += 1
            continue
        written += 1
        if not args.dry_run:
            path.write_text(text, encoding="utf-8")

    reasons: dict[str, int] = {}
    for reason in skipped.values():
        key = reason.split(":")[0] if reason.startswith(("feed failed", "rejected by")) else re.sub(r"feed offers .*", "feed disagrees with cask", reason)
        reasons[key] = reasons.get(key, 0) + 1
    print(f"{len(feeds)} Sparkle casks, {len(found)} candidates, {len(verified)} verified")
    print(f"{written} written{' (dry run)' if args.dry_run else ''}, {unchanged} unchanged")
    for reason, count in sorted(reasons.items(), key=lambda item: -item[1]):
        print(f"  skipped {count:4}: {reason}")
    # Only a full survey can tell which generated entries stopped verifying.
    stale = [] if only else sorted(generated - verified)
    if stale:
        print(f"{len(stale)} generated entries no longer verify (not removed; check by hand): {', '.join(stale)}")
    if args.dry_run:
        for token, reason in sorted(skipped.items()):
            print(f"{token}: {reason}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
